cabal test: Update cabal test and regression test for github and travis CI

diff --git a/scripts/regression_test b/scripts/regression_test
--- a/scripts/regression_test
+++ b/scripts/regression_test
@@ -7,10 +7,18 @@ if [ -z "${TMPDIR}" ] ; then
     TMPDIR=/tmp
 fi
 if [ -z "${TESTDIR}" ] ; then
-    TESTDIR=tmp/language_c
+    TESTDIR=regression_test
 fi
 if [ -z "${DEFAULT_BROWSER}" ] ; then
     DEFAULT_BROWSER=firefox
+fi
+if [ -e ".git" ] ; then
+    HAS_GIT=1
+elif [ -e "_darcs" ] ; then
+    HAS_DARCS=1
+else
+    echo "Please run this script from the language-c repository (darcs or git)" >&2
+    exit 1
 fi
 
 # messages
@@ -33,13 +41,22 @@ if [ ! -d "$TESTDIR" ] ; then
     savedir="$(pwd)"
     mkdir -p $(dirname "${TESTDIR}")
     pushd $(dirname "${TESTDIR}")
-    darcs clone "${savedir}" $(basename "${TESTDIR}")
+    if [ $HAS_GIT -eq 1 ] ; then
+        git clone "${savedir}" $(basename "${TESTDIR}") || die "Failed to clone local git repo"
+    else
+        darcs clone "${savedir}" $(basename "${TESTDIR}") || die "Failed to clone local darcs repo"
+    fi
     popd
 fi
 
 # update
 cd "${TESTDIR}"
-darcs pull || die "darcs pull (from local HEAD) failed"
+if [ $HAS_GIT -eq 1 ] ; then
+    git pull origin master || die "git pull (from local HEAD) failed"
+else
+    darcs pull || die "darcs pull (from local HEAD) failed"
+fi
+
 
 # regression test
 echo "Building via cabal"
